### ISSUE TITLE
Top-level statement closure parsing error

### ISSUE THREAD

**Issue by SIDOVSKY** [EamonNerbonne/ExpressionToCode#195]
C# 9 top level program:
```csharp
using System;
using System.Linq.Expressions;
using ExpressionToCodeLib;

var variableToCapture = "Capture Me :)";
Expression<Func<object>> closureExpression = () => variableToCapture.ToString();
ExpressionToCode.ToCode(closureExpression);
```
throws:
```
System.ArgumentException: Unusual type, heuristics uncertain:<>c__DisplayClass0_0
   at ExpressionToCodeLib.Internal.ReflectionHelpers.GuessTypeClass(Type type) in E:\vcs\ExpressionToCode\ExpressionToCodeLib\Internal\ReflectionHelpers.cs:line 118
   at ExpressionToCodeLib.Internal.ExpressionToCodeImpl.isThisRef(Expression e) in E:\vcs\ExpressionToCode\ExpressionToCodeLib\Internal\ExpressionToCodeImpl.cs:line 268
   at ExpressionToCodeLib.Internal.ExpressionToCodeImpl.DispatchMemberAccess(Expression e) in E:\vcs\ExpressionToCode\ExpressionToCodeLib\Internal\ExpressionToCodeImpl.cs:line 285
   at ExpressionToCodeLib.Internal.ExpressionTypeDispatcher.ExpressionDispatch[T](IExpressionTypeDispatch`1 dispatcher, Expression e) in E:\vcs\ExpressionToCode\ExpressionToCodeLib\Internal\ExpressionTypeDispatch.Generated.cs:line 121
   at ExpressionToCodeLib.Internal.ExpressionToCodeImpl.SingleChildDispatch(Expression child) in E:\vcs\ExpressionToCode\ExpressionToCodeLib\Internal\ExpressionToCodeImpl.cs:line 40
   at ExpressionToCodeLib.Internal.ExpressionToCodeImpl.NestExpression(Nullable`1 parentType, Expression child, Boolean parensIfEqualRank)+MoveNext() in E:\vcs\ExpressionToCode\ExpressionToCodeLib\Internal\ExpressionToCodeImpl.cs:line 32
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   at ExpressionToCodeLib.Internal.ExpressionToCodeImpl.KidsBuilder.Add(IEnumerable`1 nodes) in E:\vcs\ExpressionToCode\ExpressionToCodeLib\Internal\ExpressionToCodeImpl.cs:line 96
   at ExpressionToCodeLib.Internal.ExpressionToCodeImpl.StringifyMethodName(MethodCallExpression mce, MethodInfo method, Expression objExpr) in E:\vcs\ExpressionToCode\ExpressionToCodeLib\Internal\ExpressionToCodeImpl.cs:line 469
   at ExpressionToCodeLib.Internal.ExpressionToCodeImpl.DispatchCall(Expression e) in E:\vcs\ExpressionToCode\ExpressionToCodeLib\Internal\ExpressionToCodeImpl.cs:line 392
   at ExpressionToCodeLib.Internal.ExpressionTypeDispatcher.ExpressionDispatch[T](IExpressionTypeDispatch`1 dispatcher, Expression e) in E:\vcs\ExpressionToCode\ExpressionToCodeLib\Internal\ExpressionTypeDispatch.Generated.cs:line 104
   at ExpressionToCodeLib.Internal.ExpressionToCodeImpl.SingleChildDispatch(Expression child) in E:\vcs\ExpressionToCode\ExpressionToCodeLib\Internal\ExpressionToCodeImpl.cs:line 40
   at ExpressionToCodeLib.Internal.ExpressionToCodeImpl.NestExpression(Nullable`1 parentType, Expression child, Boolean parensIfEqualRank)+MoveNext() in E:\vcs\ExpressionToCode\ExpressionToCodeLib\Internal\ExpressionToCodeImpl.cs:line 32
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   at ExpressionToCodeLib.Internal.ExpressionToCodeImpl.KidsBuilder.Add(IEnumerable`1 nodes) in E:\vcs\ExpressionToCode\ExpressionToCodeLib\Internal\ExpressionToCodeImpl.cs:line 96
   at ExpressionToCodeLib.Internal.ExpressionToCodeImpl.DispatchLambda(Expression e) in E:\vcs\ExpressionToCode\ExpressionToCodeLib\Internal\ExpressionToCodeImpl.cs:line 263
   at ExpressionToCodeLib.Internal.ExpressionTypeDispatcher.ExpressionDispatch[T](IExpressionTypeDispatch`1 dispatcher, Expression e) in E:\vcs\ExpressionToCode\ExpressionToCodeLib\Internal\ExpressionTypeDispatch.Generated.cs:line 116
   at ExpressionToCodeLib.Internal.ExpressionToCodeString.ToCodeString(ExpressionToCodeConfiguration config, Expression e) in E:\vcs\ExpressionToCode\ExpressionToCodeLib\Internal\ExpressionToCodeString.cs:line 13
   at ExpressionToCodeLib.ExpressionToCodeConfiguration.ExpressionToCodeWrapper.ToCode(Expression e) in E:\vcs\ExpressionToCode\ExpressionToCodeLib\ExpressionToCodeConfiguration.cs:line 147
   at ExpressionToCodeLib.ExpressionToCode.ToCode(Expression e) in E:\vcs\ExpressionToCode\ExpressionToCodeLib\ExpressionToCode.cs:line 27
   at ExpressionToCodeLib.ExpressionToCode.ToCode[T](Expression`1 e) in E:\vcs\ExpressionToCode\ExpressionToCodeLib\ExpressionToCode.cs:line 24
```

Reproduce:
https://dotnetfiddle.net/4uTEEV

**Comment by EamonNerbonne** [comment]
Ah, of course - I'll look into it; looks superficially like this should be simple to detect.

**Comment by EamonNerbonne** [comment]
(Obviously, PR's welcome ;-) )

**Comment by EamonNerbonne** [comment]
Released as https://www.nuget.org/packages/ExpressionToCodeLib/3.4.0
